version: "3"
tasks:
  default:
    deps: [build:linux, build:windows]

  build:linux:
    dir: build
    platforms: [linux]
    cmds:
      - mkdir -p build
      - cmake ..
      - cmake --build . --config Release
      - make -j 8

  build:windows:
    dir: build
    platforms: [windows]
    cmds:
      - mkdir -p build
      - cmake .. -A Win32
      - cmake --build . --config Release
      - make -j 8