version: "3"

tasks:
  default:
    deps: [build:linux]

  build:all:
    desc: Build for Linux using Earthly
    cmds:
      - earthly +all

  build:linux:
    desc: Build for Linux using Earthly
    cmds:
      - earthly +build-linux

  export:
    desc: Export Linux artifacts to host
    cmds:
      - earthly +export-artifacts

  package:
    desc: Create distribution packages for Linux
    cmds:
      - earthly +package

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build/
      - rm -rf dist/
      - rm -rf artifacts/
      - earthly prune